stages:
  - test

test-arduino:
  image: python:2.7
  stage: test
  before_script:
    - pip install -U platformio
    # Install atmelavr library
    - platformio platforms install atmelavr
    # Install MsTimer2 library
    - platformio lib install 137 584
  script:
    - platformio ci --board=uno
