language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=arduino/arduino.ino
install:
    - pip install -U platformio
    # Install MsTimer2 and IQRF library
    - platformio lib install 137 584
script:
    - platformio ci --board=uno --board=leonardo --board=diecimilaatmega168 --board=megaatmega2560 --board=megaatmega1280
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/48475240650828086652
    on_success: change
    on_failure: always
    on_start: never
