language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=src/src.ino
install:
    - pip install -U platformio
    # Install MsTimer2 library
    - platformio lib install 137
script:
    - platformio ci --lib="lib/IQRF/" --board=uno --board=nanoatmega328
