language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=src/src.ino
install:
    - pip install -U platformio
script:
    - platformio ci --lib="lib/MsTimer2-1.1/" --lib="lib/IQRF/" --board=uno
